# Generated by Django 3.2.3 on 2021-05-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='is_love',
            new_name='is_live',
        ),
    ]
