# Generated by Django 3.2.3 on 2021-05-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesharer', '0002_rename_is_love_volunteer_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='username',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
