# Generated by Django 3.2.3 on 2021-05-25 15:05

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('timesharer', '0003_auto_20210524_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
