# Generated by Django 3.2.3 on 2021-05-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0005_auto_20210525_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='applied_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='timesharer.opportunity'),
        ),
    ]
