# Generated by Django 3.2.3 on 2021-05-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0006_alter_volunteer_applied_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='applied_to',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='volunteers',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='timesharer.volunteer'),
        ),
    ]
