# Generated by Django 3.2.3 on 2021-06-01 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesharer', '0008_auto_20210531_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='volunteers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timesharer.volunteer'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
