# Generated by Django 3.2.3 on 2021-05-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0008_auto_20210531_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
