# Generated by Django 3.2.3 on 2021-06-01 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0009_auto_20210601_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='applied_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='timesharer.opportunity'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
    ]
