# Generated by Django 3.2.3 on 2021-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0010_auto_20210601_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(default='Location', max_length=20),
        ),
    ]
