# Generated by Django 3.2.3 on 2021-06-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesharer', '0011_opportunity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
